# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 683)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.gui = QtWidgets.QFrame(self.centralwidget)
        self.gui.setGeometry(QtCore.QRect(10, 10, 493, 683))
        self.gui.setObjectName("gui")
        self.gridLayout = QtWidgets.QGridLayout(self.gui)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btSd = QtWidgets.QPushButton(self.gui)
        self.btSd.setMinimumSize(QtCore.QSize(175, 100))
        self.btSd.setFlat(True)
        self.btSd.setObjectName("btSd")
        self.gridLayout.addWidget(self.btSd, 1, 0, 1, 1)
        self.btConfig = QtWidgets.QPushButton(self.gui)
        self.btConfig.setMinimumSize(QtCore.QSize(100, 100))
        self.btConfig.setFlat(True)
        self.btConfig.setObjectName("btConfig")
        self.gridLayout.addWidget(self.btConfig, 0, 2, 1, 1)
        self.btUsb = QtWidgets.QPushButton(self.gui)
        self.btUsb.setMinimumSize(QtCore.QSize(175, 100))
        self.btUsb.setFlat(True)
        self.btUsb.setObjectName("btUsb")
        self.gridLayout.addWidget(self.btUsb, 0, 0, 1, 1)
        self.btAbbruch = QtWidgets.QPushButton(self.gui)
        self.btAbbruch.setMinimumSize(QtCore.QSize(100, 100))
        self.btAbbruch.setFlat(True)
        self.btAbbruch.setObjectName("btAbbruch")
        self.gridLayout.addWidget(self.btAbbruch, 3, 0, 1, 1)
        self.btAccept = QtWidgets.QPushButton(self.gui)
        self.btAccept.setMinimumSize(QtCore.QSize(100, 100))
        self.btAccept.setFlat(True)
        self.btAccept.setObjectName("btAccept")
        self.gridLayout.addWidget(self.btAccept, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.btTrigger = QtWidgets.QPushButton(self.gui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTrigger.sizePolicy().hasHeightForWidth())
        self.btTrigger.setSizePolicy(sizePolicy)
        self.btTrigger.setFlat(True)
        self.btTrigger.setObjectName("btTrigger")
        self.gridLayout.addWidget(self.btTrigger, 2, 0, 1, 3)
        self.bild = QtWidgets.QLabel(self.centralwidget)
        self.bild.setGeometry(QtCore.QRect(560, 70, 231, 331))
        self.bild.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bild.setText("")
        self.bild.setObjectName("bild")
        self.lblZahl = QtWidgets.QLabel(self.centralwidget)
        self.lblZahl.setGeometry(QtCore.QRect(450, 150, 493, 383))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lblZahl.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(300)
        self.lblZahl.setFont(font)
        self.lblZahl.setScaledContents(True)
        self.lblZahl.setAlignment(QtCore.Qt.AlignCenter)
        self.lblZahl.setObjectName("lblZahl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fotobox"))
        self.btSd.setText(_translate("MainWindow", "SD"))
        self.btConfig.setText(_translate("MainWindow", "Config"))
        self.btUsb.setText(_translate("MainWindow", "USB"))
        self.btAbbruch.setText(_translate("MainWindow", "Abbruch"))
        self.btAccept.setText(_translate("MainWindow", "OK"))
        self.btTrigger.setText(_translate("MainWindow", "Trigger"))
        self.lblZahl.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
